import mongoose, { Document, Schema } from 'mongoose';

export interface IVariant {
  size: string;
  stock: number;
  sku: string;
}

export interface IMetalOption {
  type: 'yellow-gold' | 'white-gold' | 'rose-gold' | 'platinum' | 'silver';
  karat?: '9ct' | '14ct' | '18ct';
  priceModifier: number;
  images: string[];
  isDefault: boolean;
}

export interface IWeightBySize {
  size: string;
  weightGrams: number;
}

export interface IProduct extends Document {
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  category: mongoose.Types.ObjectId;
  subCategory?: string;
  basePrice: number;
  salePrice?: number;
  competitorPrice?: number;   // "High Street Price" for comparison banner
  images: string[];
  videos?: string[];
  metalOptions: IMetalOption[];
  variants: IVariant[];
  tags: string[];
  style?: string;
  gemstone?: string;
  settingType?: string;
  // Ring-specific fields
  bandStyle?: 'plain' | 'pave' | 'half-pave' | 'channel' | 'twisted';
  shankWidth?: 'slim' | 'standard' | 'large';
  weightBySize: IWeightBySize[]; // weight per ring size for live gold pricing
  isEngravable: boolean;
  isFeatured: boolean;
  isBestseller: boolean;
  isNewArrival: boolean;
  isActive: boolean;
  averageRating: number;
  reviewCount: number;
  soldCount: number;
  weight?: number;
  dimensions?: string;
  certification?: string;
  deliveryDays: number;
  metaTitle?: string;
  metaDescription?: string;
  isRingBuilder: boolean;        // true = routes to ring builder; false = standard product page
  source?: string;               // 'hanron' | undefined — where the product was imported from
  aiGenerated?: boolean;
  model3dUrl?: string;           // GLB URL generated by Meshy.ai
  model3dPreview?: string;       // Thumbnail for 3D model
  lifestyleImageUrl?: string;    // AI-generated "worn" lifestyle photo (Replicate)
  createdAt: Date;
  updatedAt: Date;
}

const metalOptionSchema = new Schema<IMetalOption>({
  type: { type: String, enum: ['yellow-gold', 'white-gold', 'rose-gold', 'platinum', 'silver'], required: true },
  karat: { type: String, enum: ['9ct', '14ct', '18ct'] },
  priceModifier: { type: Number, default: 0 },
  images: [String],
  isDefault: { type: Boolean, default: false },
});

const variantSchema = new Schema<IVariant>({
  size: { type: String, required: true },
  stock: { type: Number, required: true, default: 0 },
  sku: { type: String, required: true },
});

const weightBySizeSchema = new Schema<IWeightBySize>({
  size: { type: String, required: true },
  weightGrams: { type: Number, required: true },
}, { _id: false });

const productSchema = new Schema<IProduct>(
  {
    name: { type: String, required: true, trim: true },
    slug: { type: String, required: true, unique: true, lowercase: true },
    description: { type: String, default: '' },
    shortDescription: { type: String, required: true },
    category: { type: Schema.Types.ObjectId, ref: 'Category', required: true },
    subCategory: String,
    basePrice: { type: Number, required: true, min: 0 },
    salePrice: { type: Number, min: 0 },
    images: [{ type: String, required: true }],
    videos: [String],
    metalOptions: [metalOptionSchema],
    variants: [variantSchema],
    tags: [String],
    style: String,
    gemstone: String,
    settingType: String,
    bandStyle: { type: String, enum: ['plain', 'pave', 'half-pave', 'channel', 'twisted'] },
    shankWidth: { type: String, enum: ['slim', 'standard', 'large'] },
    weightBySize: [weightBySizeSchema],
    competitorPrice: { type: Number, min: 0 },
    isRingBuilder: { type: Boolean, default: false },
    source: String,
    aiGenerated: { type: Boolean, default: false },
    isEngravable: { type: Boolean, default: false },
    isFeatured: { type: Boolean, default: false },
    isBestseller: { type: Boolean, default: false },
    isNewArrival: { type: Boolean, default: true },
    isActive: { type: Boolean, default: true },
    averageRating: { type: Number, default: 0, min: 0, max: 5 },
    reviewCount: { type: Number, default: 0 },
    soldCount: { type: Number, default: 0 },
    weight: Number,
    dimensions: String,
    certification: String,
    deliveryDays: { type: Number, default: 7 },
    metaTitle: String,
    metaDescription: String,
    model3dUrl: String,
    model3dPreview: String,
    lifestyleImageUrl: String,
  },
  { timestamps: true }
);

productSchema.index({ name: 'text', description: 'text', tags: 'text' });
productSchema.index({ category: 1, isActive: 1 });
productSchema.index({ isActive: 1, createdAt: -1 });
productSchema.index({ isActive: 1, isFeatured: 1 });
productSchema.index({ isActive: 1, isBestseller: 1, soldCount: -1 });
productSchema.index({ isActive: 1, isRingBuilder: 1 });
productSchema.index({ isActive: 1, basePrice: 1 });

export default mongoose.model<IProduct>('Product', productSchema);
