/**
 * fal.ai service
 * Handles:
 *   - Metal colour variant images (image editing via FLUX Kontext)
 *
 * Lifestyle photos and side-view photos are now generated by Gemini
 * (see gemini.service.ts).
 */

import { fal } from '@fal-ai/client';

function configure() {
  const key = process.env.FAL_KEY;
  if (!key) throw new Error('FAL_KEY not set in environment');
  fal.config({ credentials: key });
}

/* ══════════════════════════════════════════════════════════════════════════════
   HELPERS
══════════════════════════════════════════════════════════════════════════════ */

/**
 * fal.ai cannot download arbitrary external URLs.
 * This uploads an image to fal storage and returns a fal CDN URL that the
 * model can always access.
 */
async function uploadToFalStorage(imageUrl: string): Promise<string> {
  const resp = await fetch(imageUrl, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; SterlingBot/1.0)' },
  });
  if (!resp.ok) throw new Error(`Could not fetch image (${resp.status}): ${imageUrl}`);

  const buffer = Buffer.from(await resp.arrayBuffer());
  const contentType = resp.headers.get('content-type') || 'image/jpeg';
  const ext = contentType.includes('png') ? 'png' : contentType.includes('webp') ? 'webp' : 'jpg';

  const file = new File([buffer], `product.${ext}`, { type: contentType });
  const falUrl = await fal.storage.upload(file);
  console.log('[fal] uploaded to fal storage:', falUrl);
  return falUrl;
}

/* ══════════════════════════════════════════════════════════════════════════════
   METAL COLOUR VARIANT  —  fal-ai/flux-pro/kontext  (image editing)
══════════════════════════════════════════════════════════════════════════════ */

export async function generateMetalVariantImage(
  imageUrl: string,
  metalType: string,
  karat?: string,
): Promise<{ predictionId: string }> {
  configure();

  const falImageUrl = await uploadToFalStorage(imageUrl);

  const metalDescriptions: Record<string, string> = {
    'yellow-gold': `Change the metal to ${karat || '18ct'} yellow gold — rich warm golden colour, polished finish. Keep the exact ring design, shape, gemstones, and setting unchanged. Pure white studio background.`,
    'white-gold':  `Change the metal to ${karat || '18ct'} white gold — bright cool silver-white polished metal. Keep the exact ring design, shape, gemstones, and setting unchanged. Pure white studio background.`,
    'rose-gold':   `Change the metal to ${karat || '18ct'} rose gold — warm blush-pink polished metal. Keep the exact ring design, shape, gemstones, and setting unchanged. Pure white studio background.`,
    'platinum':    `Change the metal to platinum — cool grey polished premium metal. Keep the exact ring design, shape, gemstones, and setting unchanged. Pure white studio background.`,
    'silver':      `Change the metal to sterling silver — bright neutral polished metal. Keep the exact ring design, shape, gemstones, and setting unchanged. Pure white studio background.`,
  };

  const prompt = metalDescriptions[metalType] ?? metalDescriptions['yellow-gold'];
  console.log('[fal] metal variant start | metal:', metalType);

  const { request_id } = await fal.queue.submit('fal-ai/flux-pro/kontext', {
    input: {
      prompt,
      image_url: falImageUrl,
      num_images: 1,
    },
  });

  return { predictionId: request_id };
}

export async function checkMetalVariantStatus(requestId: string): Promise<{
  status: string;
  output?: string[];
  error?: string;
}> {
  configure();
  try {
    const status = await fal.queue.status('fal-ai/flux-pro/kontext', {
      requestId,
      logs: false,
    });

    if (status.status === 'COMPLETED') {
      const result = await fal.queue.result('fal-ai/flux-pro/kontext', { requestId }) as {
        data: { images: { url: string }[] };
      };
      const url = result.data?.images?.[0]?.url;
      return { status: 'succeeded', output: url ? [url] : [] };
    }

    return { status: 'processing' };
  } catch (err) {
    console.error('[fal] status check error:', err);
    return { status: 'failed', error: String(err) };
  }
}
